### ISSUE TITLE
Import PHP examples

### ISSUE THREAD

**Issue by ar-x** [ar-x/turtlecoin-api-docs-site#1]
https://github.com/turtlecoin/turtlecoin-walletd-rpc-php

**Comment by ar-x** [comment]
@timmcleod Just so that we don't step on each other. Is it ok if I assign you this issue, and the [shell one] to myself?

**Comment by timmcleod** [comment]
Sure, that works. I was traveling over the weekend, so I haven’t done anything beyond what’s already merged, but should be able to work on it some today or tonight.

**Comment by ar-x** [comment]
Sure, no rush. Thats just me being excited! We can also run bounties or ask others for help _if needed_.  Since its all 1 md file, we might run into git conflicts. Lets see.

**Comment by timmcleod** [comment]
First pass at this is done. https://github.com/ar-x/turtlecoin-wiki/pull/5
