### ISSUE TITLE
Move under Turtlecoin

### ISSUE THREAD

**Issue by ar-x** [ar-x/turtlecoin-api-docs-site#13]
Hi @Rocksteadytc,

As planned earlier, I would like to move this under Turtlecoin

* [x] Would you `fork` this repo, and all future updates be made there?, or should I just transfer this repo directly to you so that it can be put under the organization?

* This deploys to github pages.
  * [x] Can you create a CNAME: api-docs.turtlecoin.lol => turtlecoin.github.io.
  * [ ] Once this repo is on turtlecoin GH org, enable Travis CI for it. Once thats done –
     * [x] Remove the `env` key from `.travis.yml`.
     * [ ] Create a personal access token with `repo > public_repo` access.
     * [ ] Add it as `GITHUB_TOKEN` to `.travis.yml`, via `travis encrypt GITHUB_TOKEN="secretvalue" --add`.

Thanks.

cc @timmcleod @SoreGums

**Comment by RocksteadyTC** [comment]
Sure, I can do this Monday

**Comment by RocksteadyTC** [comment]
done

**Comment by ar-x** [comment]
@RocksteadyTC Thanks! Though its partially done. See the updated checklist above.

The Travis CI is here: https://travis-ci.org/turtlecoin/turtlecoin-api-docs-site/
