### ISSUE TITLE
Import Shell examples

### ISSUE THREAD

**Issue by ar-x** [ar-x/turtlecoin-api-docs-site#3]
Via `curl` https://wiki.bytecoin.org/wiki/Reset_-_Bytecoin_RPC_Wallet_API

**Comment by ar-x** [comment]
Unassigning from myself as I might not be able to get to it immediately. If anyone wants to do it please go ahead.

cc @timmcleod

**Comment by timmcleod** [comment]
First pass at this is done. https://github.com/ar-x/turtlecoin-wiki/pull/4
