### ISSUE TITLE
Import Go examples

### ISSUE THREAD

**Issue by ar-x** [ar-x/turtlecoin-api-docs-site#5]
https://github.com/turtlecoin/turtlecoin-walletd-rpc-go

**Comment by timmcleod** [comment]
Ok, bebop said that turtlecoin-walletd-rpc-go (https://github.com/turtlecoin/turtlecoin-walletd-rpc-go) is non stable and in development right now, so we need to skip the Go lib for now.

**Comment by timmcleod** [comment]
Close for now?

**Comment by ar-x** [comment]
;)
