### ISSUE TITLE
Bytecoin attribution

### ISSUE THREAD

**Issue by ar-x** [ar-x/turtlecoin-api-docs-site#6]

**Comment by ar-x** [comment]
@SoreGums @ZedPea @RocksteadyTC – no rush on this. Just wanted to pick your minds on the best way to credit the Bytecoin wiki. cc @timmcleod

**Comment by RocksteadyTC** [comment]
https://creativecommons.org/licenses/by-sa/3.0/

**Comment by ar-x** [comment]
Done. See https://hinata-104.shadow-clone-jutsu.com/#license
