### ISSUE TITLE
Finalize frontend

### ISSUE THREAD

**Issue by ar-x** [ar-x/turtlecoin-api-docs-site#7]
gather feedback.

**Comment by SoreGums** [comment]
In other API docs, there have been colours used to highlight common things.
Like a POST request - the word post is green highlighted. Therefore, all the greens are POST.

I will see if I can find examples. Haven't been successful yet...

**Comment by ar-x** [comment]
@SoreGums - some other instances of Slate are here: https://github.com/lord/slate#companies-using-slate

**Comment by ar-x** [comment]
@timmcleod Based on our convo earlier, the right col is not edge to edge now. The left col needs a slight change in the aside HTML in `md`s to appear well.

<img width="1264" alt="example" src="https://user-images.githubusercontent.com/37969038/40257146-b213f306-5b0a-11e8-9b36-8bccfc6e907b.png">

```html
<aside class="notice">
  <div>some content ... </div>
</aside>
```
note the div inside. in the absence of it, it would appear edge to edge.

**Comment by ar-x** [comment]
@timmcleod The newlines here look a little off to me

<img width="494" alt="example" src="https://user-images.githubusercontent.com/37969038/40257730-e986e0c6-5b0c-11e8-8b3a-1b39c640f969.png">


Usually, i wouldn't put a line break unless its a multi line block. (the 'surround multi line blocks in newline rule' ;) )

So valid forms:

```js
const a = 1;
const b = 2;
```

```js
const a = 1;

if (a === b) {
  ....
}

const b = 2;
```

```js
const a = {
 ....
};

const b = 1;

const c = {
 ....
};
```

**Comment by timmcleod** [comment]
Nice @ar-x looks good. I hadn't considered the `aside`'s, but I like it.

I'm good with that. I like space, but I'm weird like that. :)

**Comment by timmcleod** [comment]
https://github.com/ar-x/turtlecoin-wiki/pull/6

**Comment by timmcleod** [comment]
Noticed that the font color needs to be changed in the code examples that are highlighted by the search highlight. Dropping it here for later.

<img width="1305" alt="search-highlight" src="https://user-images.githubusercontent.com/1099280/40273834-0dc642e0-5b96-11e8-9181-21d592d143e5.png">

**Comment by ar-x** [comment]
@timmcleod Fixed!
